/* Auto-generated by export_weights.py — DO NOT EDIT */
#ifndef RNN_DATA_H_
#define RNN_DATA_H_

#include "rnn.h"

/* Custom RNNoise model: 65 features → 32 gains + 1 VAD */
extern const struct RNNModel rnnoise_model_custom;

#endif /* RNN_DATA_H_ */
